config/routes.rb
SetPoint::Application.routes.draw do

  resources :thermostats

  resources :locations do
    resources :thermostats
  end

  root :to => 'locations#demand'

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :thermostats
  validates :address, presence: true, uniqueness: true

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  acts_as_gmappable
  def gmaps4rails_address
    "#{self.address}"
  end

  def gmaps
    true
  end

end

app/models/thermostat.rb
class Thermostat < ActiveRecord::Base
  belongs_to :location

  acts_as_gmappable
  delegate :address, :latitude, :longitude, :gmaps4rails_address, :to => :location

  validates :location_id, presence: true
  validates :set_point, presence: true
  validates :serial_number, presence: true, uniqueness: true

  # requires the temp setting and an array of thermostats
  def self.demand_set_point(setting, tstats = [])
    return if setting.blank?
    tstats = all if tstats.blank?
    tstats.each do |t|
      t.update_attribute(:set_point, setting)
    end
  end

  def gmaps4rails_title
    "Set Point #{self.set_point}"
  end

  def gmaps4rails_infowindow
    "<h5>Thermostat</h5><p>S/N #{self.serial_number}<br/>Set Point #{self.set_point}</p>"
  end

  def gmaps
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  def demand
    @center = Location.new do |l|
      l.address = params[:address].present? ? params[:address] : "Broomfield, CO"
      l.geocode
    end

    @radius = params[:radius].present? ? params[:radius].to_i : 10

    if params[:commit].present? # PUT
      @locations = Location.near(@center.address.to_s, @radius, :order => :distance)
      @locations.collect{|l| l.thermostats.demand_set_point(params[:setting].to_i)} if params[:setting].present?
    else
      @locations = Location.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :ok }
    end
  end
end

app/controllers/thermostats_controller.rb
class ThermostatsController < ApplicationController
  # GET /thermostats
  # GET /thermostats.json
  def index
    @thermostats = Thermostat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @thermostats }
    end
  end

  # GET /thermostats/1
  # GET /thermostats/1.json
  def show
    @thermostat = Thermostat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thermostat }
    end
  end

  # GET /thermostats/new
  # GET /thermostats/new.json
  def new
    @thermostat = Thermostat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thermostat }
    end
  end

  # GET /thermostats/1/edit
  def edit
    @thermostat = Thermostat.find(params[:id])
  end

  # POST /thermostats
  # POST /thermostats.json
  def create
    @thermostat = Thermostat.new(params[:thermostat])

    respond_to do |format|
      if @thermostat.save
        format.html { redirect_to @thermostat, notice: 'Thermostat was successfully created.' }
        format.json { render json: @thermostat, status: :created, location: @thermostat }
      else
        format.html { render action: "new" }
        format.json { render json: @thermostat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /thermostats/1
  # PUT /thermostats/1.json
  def update
    @thermostat = Thermostat.find(params[:id])

    respond_to do |format|
      if @thermostat.update_attributes(params[:thermostat])
        format.html { redirect_to @thermostat, notice: 'Thermostat was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @thermostat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thermostats/1
  # DELETE /thermostats/1.json
  def destroy
    @thermostat = Thermostat.find(params[:id])
    @thermostat.destroy

    respond_to do |format|
      format.html { redirect_to thermostats_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper

  def add_markers
    markers = []
    @locations.collect do |l|
      markers << l.thermostats
    end

    markers.flatten.to_gmaps4rails
  end

  def demand_circle
    "[
     {'lng': #{@center.longitude}, 'lat': #{@center.latitude}, 'radius': #{@radius*1609.34}}
    ]"
  end

  def addresses_found
    return "No thermostats found within #{@radius} miles of #{@center.address}" if @locations.size == 0
    render 'responses'
  end

  def hash_for_gmaps
    { 'circles' => {'data' => demand_circle},
      'markers' => { 'data' => add_markers,
                     'options' => { 'randomize' => true,
                                    'max_random_distance' => 1
                     }
      }}
  end
end

app/helpers/thermostats_helper.rb
module ThermostatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SetPoint</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= yield :scripts %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    Enter the Address: <%= f.text_field :address %><br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/_responses.html.erb
<table>
  <tr>
    <th>Address</th>
    <th>Serial Number</th>
    <th>Set Point</th>
  </tr>

<% @locations.each do |location| %>
      <% location.thermostats.each do |tstat| %>
          <tr>
            <td><%= tstat.location.address %></td>
            <td><%= tstat.serial_number %></td>
            <td><%= tstat.set_point %></td>
          </tr>
      <% end %>
<% end %>
</table>

app/views/locations/demand.html.erb
<h1>Demand Response Page</h1>

<div id="demand_form" style="text-align: right">
  <%= form_tag('/', :method => :put) do %>
  <table>
    <tr>
      <td>Enter the Demand Response center address:</td><td><%= text_field_tag :address %></td>
    </tr>
    <tr>
      <td>Enter the Demand Radius in Miles:</td><td><%= text_field_tag :radius %></td>
    </tr>
    <tr>
      <td>Enter the thermostat Set Point:</td><td><%= text_field_tag :setting %></td>
    </tr>
    <tr><td/><td><%= submit_tag 'Find Thermostats' %></td></tr>
  </table>
  <% end %>
</div>

<div id="response_locations">
  <%= addresses_found %>
</div>

<br/><br/>
<h3>Current Demand Center: <%= @center.address %></h3>

<%= gmaps(hash_for_gmaps) %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Thermostat Locations</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Number of thermostats</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.address %></td>
    <td><%= location.thermostats.count %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>Add a location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Address</h1>
Address <%= @location.address %>
<br/><br/>

<h3>Location's Thermostats</h3>

<table>
  <tr>
    <th>Thermostat - SN</th>
    <th>Thermostat - Set Point</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @location.thermostats.each do |thermostat| %>
      <tr>
        <td><%= thermostat.serial_number %></td>
        <td><%= thermostat.set_point %></td>
        <td><%= link_to 'Show', location_thermostat_path(thermostat) %></td>
        <td><%= link_to 'Edit', edit_location_thermostat_path(thermostat) %></td>
        <td><%= link_to 'Destroy', location_thermostat_path(thermostat), confirm: 'Are you sure?', method: :delete %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'Add a Thermostat', new_location_thermostat_path(@location) %> |
<%= link_to 'Edit this location', edit_location_path(@location) %> |
<%= link_to 'Back to Demand Response Page', locations_path %>

app/views/thermostats/_form.html.erb
<%= form_for(@thermostat) do |f| %>
  <% if @thermostat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thermostat.errors.count, "error") %> prohibited this thermostat from being saved:</h2>

      <ul>
      <% @thermostat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thermostats/edit.html.erb
<h1>Editing thermostat</h1>

<%= render 'form' %>

<%= link_to 'Show', @thermostat %> |
<%= link_to 'Back', thermostats_path %>

app/views/thermostats/index.html.erb
<h1>Listing thermostats</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @thermostats.each do |thermostat| %>
  <tr>
    <td><%= link_to 'Show', thermostat %></td>
    <td><%= link_to 'Edit', edit_thermostat_path(thermostat) %></td>
    <td><%= link_to 'Destroy', thermostat, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thermostat', new_thermostat_path %>

app/views/thermostats/new.html.erb
<h1>New thermostat</h1>

<%= render 'form' %>

<%= link_to 'Back', thermostats_path %>

app/views/thermostats/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_thermostat_path(@thermostat) %> |
<%= link_to 'Back', thermostats_path %>